// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>

namespace ZofraTacna
{
    public partial class Default
    {
        protected global::System.Web.UI.WebControls.Literal litAvatar;
        protected global::System.Web.UI.WebControls.Literal litNombre;
        protected global::System.Web.UI.WebControls.Literal litRol;
        protected global::System.Web.UI.WebControls.Literal litBienvenido;
        protected global::System.Web.UI.WebControls.Literal litDocumentosRecientes;
        protected global::System.Web.UI.WebControls.Literal litActividadSistema;
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Literal litPendientes;
        protected global::System.Web.UI.WebControls.Literal litCompletados;
        protected global::System.Web.UI.WebControls.Literal litUsuarios;
        protected global::System.Web.UI.WebControls.Panel pnlHerramientas;
        protected global::System.Web.UI.WebControls.Button btnCerrarSesion;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl badgeBandeja;
    }
}
