// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>

namespace ZofraTacna
{
    public partial class Firmante
    {
        protected global::System.Web.UI.WebControls.Literal litAvatar;
        protected global::System.Web.UI.WebControls.Literal litNombre;
        protected global::System.Web.UI.WebControls.Literal litRol;
        protected global::System.Web.UI.WebControls.Literal litBienvenido;
        protected global::System.Web.UI.WebControls.Literal litBadgeBandeja;
        protected global::System.Web.UI.WebControls.Literal litPendientes;
        protected global::System.Web.UI.WebControls.Literal litFirmados;
        protected global::System.Web.UI.WebControls.Literal litTareas;
        protected global::System.Web.UI.WebControls.Literal litTotalAlertas;
        protected global::System.Web.UI.WebControls.Panel pnlRequiereAtencion;
        protected global::System.Web.UI.WebControls.Panel pnlSinAlertas;
        protected global::System.Web.UI.WebControls.Repeater rptAlertas;
        protected global::System.Web.UI.WebControls.Button btnCerrarSesion;
    }
}
